### ISSUE TITLE
"Your configuration files are not serializable." when running `php artisan config:cache`

### ISSUE THREAD

**Issue by thyseus** [borestad/blocklist-abuseipdb#7]
```
php artisan config:cache
```
gives me:
```
In ConfigCacheCommand.php line 73:
Your configuration files are not serializable.
In config.php line 13:
Call to undefined method Closure::__set_state()
exit code 1 (General error)
```
because of a `fn()` in the config file. 

Please provide a solution where config caching (`php artisan optimize`) is possible.

Thanks a lot for this great package!

**Comment by borestad** [comment]
Hi!
Sorry, this package contains zero amount of PHP, only ips in text format. You have debug your application layer  😊
